"""Membuat tabel

Revision ID: efab23e6e32a
Revises: 
Create Date: 2026-07-23 21:57:33.393554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efab23e6e32a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('masked_password', sa.String(length=50), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('strength', sa.String(length=20), nullable=False),
    sa.Column('rules_passed', sa.Integer(), nullable=False),
    sa.Column('final_state', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('password_history')
    # ### end Alembic commands ###
